### ISSUE TITLE
How to properly use material-icons

### ISSUE THREAD

**Issue by hau1** [maximegris/angular-electron#228]
Hi,

I'd like to use google material icons in my electron app. As the app will be also used offline, I need to pack it inside the app. How is this done properly?
I've tried to npm material-icons --> then add the css in the angular-cli.json and to 
@import "../node_modules/material-icons/css/material-icons.css"

It's just not working...

What's the right way of using it?

**Comment by hervehobbes** [comment]
> It's just not working...
is the worst thing you can say !
Describe what's happening, the error messages for example.

**Comment by hau1** [comment]
I do not get any error message, this is what I meant by "it's just not working...."; 
so i get no error message in the console and the instead of the icon it displays only the icons name.

I also tried to include it inside the index.html, the result has been the same

**Comment by hervehobbes** [comment]
Activate the Chrome Dev Tools and see if there is any error message

**Comment by ngfelixl** [comment]
I successfully used 'offline' material design icons with usage of <mat-icon> tags by @angular/material. At first I installed needed packages

```bash
yarn add material-design-icons @angular/material @angular/cdk @angular/animations --dev
```

Afterwards I added a theme.scss in the src/ directory with the following content suggested by documentation:

```scss
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(~/material-design-icons/iconfont/MaterialIcons-Regular.eot);
  src: local('Material Icons'),
    local('MaterialIcons-Regular'),
    url(~/material-design-icons/iconfont/MaterialIcons-Regular.woff2) format('woff2'),
    url(~/material-design-icons/iconfont/MaterialIcons-Regular.woff) format('woff'),
    url(~/material-design-icons/iconfont/MaterialIcons-Regular.ttf) format('truetype');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
  font-feature-settings: 'liga';
}
```

Then add
```
@import 'src/theme.scss'
```
to your style.(s)css. Nothing to be done in angular.json file. That's it.
